### ISSUE TITLE
[Bug] Add sort/filter to "Save to playlist" menu is unstable

### ISSUE THREAD

**Issue by venkat2305** [raingart/Nova-YouTube-extension#72]
*Describe the bug*
https://user-images.githubusercontent.com/55329452/226418218-becf9e8d-2c9a-4caa-8a91-8b412a38fb1d.mp4

please check the video.

also, can you change search box into dark theme so it will be consistent with the entire UI. 
Thanks

 - Browser: Chrome 999.0 
 - ...monkey 99.1 
 - Nova 6.6.1

**Comment by raingart** [comment]
The plugin is not working. Something changed in the html structure in youtube. My search function can't get text from elements.

the only thing that managed to restore is alphabetical sorting.

I am going to remove this plugin. I recommend trying other alternatives:

// alt1 - https://greasyfork.org/en/scripts/436123-youtube-save-to-playlist-filter
// alt2 - https://greasyfork.org/en/scripts/392141-youtube-save-to-playlist-incremental-search

**Comment by venkat2305** [comment]
alas, they are old. they probably are not maintained.

**Comment by raingart** [comment]
fixed the plugin. Everything works except highlighting words

**Comment by venkat2305** [comment]
its still unstable. im on chrome. 
[Rit jealous moment - YouTube.webm](https://user-images.githubusercontent.com/55329452/227446520-28d1544d-7954-4398-8c10-7b883473fa1c.webm)

**Comment by venkat2305** [comment]
oh. what do you think might be the issue.

**Comment by venkat2305** [comment]
I tried it in a new profile without any extensions. the issue still

**Comment by raingart** [comment]
try another version 2

the problem is that when filtering, the previous markers are cleared. And the data is overwritten. This will register youtube and change the data. Also, some of the data may not be read correctly and returned broken.
 
where to show the code
```
 el.innerHTML = el.innerHTML
                        .replace(/<\/?mark[^>]*>/g, ''); // clear highlight tags
```

if you add a check. disappears
```
if (el.innerHTML.includes('<mark ')) {
                     el.innerHTML = el.innerHTML
                        .replace(/<\/?mark[^>]*>/g, ''); // clear highlight tags
}
```

in the second ver option uses a different way of getting data. But it theoretically shouldn't work - but it works fine on the settings page. That's where this option is.
```
el.innerHTML = el.textContent.replace(/<\/?mark[^>]*>/g, ''); // clear highlight tags
```

**Comment by venkat2305** [comment]
the below one isn't stable/not working

**Comment by venkat2305** [comment]
Can you add a dark theme for it and make it consistent with the yt ui

**Comment by raingart** [comment]
![Screenshot from 2023-03-24 18-47-18](https://user-images.githubusercontent.com/13064767/227589079-2f86720f-4a29-46f6-9553-71b64624aaf7.png)
